# [theme]
# primaryColor = "#0EA5E9"
# # backgroundColor = "#FFFFFF"
# # secondaryBackgroundColor = "#F0F2F6"
# # textColor = "#262730"
# font = "sans serif"

[theme]
base = "dark"
primaryColor = "#0ea5e9"
font = "monospace"
